insert into public.education_modules (slug, language_code, role_context, title, body, source_note, version) values
('breathing-test-meaning', 'en', 'patient', 'What your breathing test means', 'The tool compares FEV1, FVC, and FEV1/FVC with LASI-derived Indian reference values for adults aged 45-90 years. Results must be interpreted with symptoms, examination, test quality, and local clinical guidance.', 'LASI GAMLSS/LMS reference equation package; clinical validation and local guideline review required.', 'v1'),
('warning-symptoms', 'en', 'patient', 'When to seek urgent care', 'Seek urgent care for severe breathlessness, chest pain, fainting, confusion, blue lips, coughing blood, sudden weakness, or rapidly worsening illness.', 'Safety education; not a substitute for emergency services or clinician assessment.', 'v1'),
('visit-preparation', 'en', 'patient', 'Prepare for your visit', 'Bring your medicine list, previous reports, vaccination history, symptom notes, fall history, caregiver concerns, and questions for your clinician.', 'Patient education module for shared decision-making.', 'v1'),
('breathing-test-meaning', 'hi', 'patient', 'आपकी सांस की जांच का अर्थ', 'यह उपकरण FEV1, FVC और FEV1/FVC की तुलना 45-90 वर्ष के भारतीय वयस्कों के LASI संदर्भ मूल्यों से करता है। परिणामों को लक्षणों, जांच, परीक्षण गुणवत्ता और स्थानीय मार्गदर्शन के साथ समझना चाहिए।', 'LASI संदर्भ समीकरण; स्थानीय नैदानिक समीक्षा आवश्यक।', 'v1'),
('warning-symptoms', 'hi', 'patient', 'तुरंत चिकित्सा सहायता कब लें', 'बहुत अधिक सांस फूलना, सीने में दर्द, बेहोशी, भ्रम, होंठ नीले पड़ना, खून वाली खांसी, अचानक कमजोरी या तेजी से बिगड़ती बीमारी में तुरंत सहायता लें।', 'सुरक्षा शिक्षा; आपातकालीन सेवा का विकल्प नहीं।', 'v1'),
('visit-preparation', 'hi', 'patient', 'भेंट के लिए तैयारी', 'अपनी दवा सूची, पुराने रिपोर्ट, टीकाकरण जानकारी, लक्षण नोट्स, गिरने का इतिहास, देखभालकर्ता की चिंताएं और प्रश्न साथ लाएं।', 'साझा निर्णय के लिए रोगी शिक्षा।', 'v1'),
('breathing-test-meaning', 'kn', 'patient', 'ನಿಮ್ಮ ಉಸಿರಾಟ ಪರೀಕ್ಷೆಯ ಅರ್ಥ', 'ಈ ಸಾಧನವು FEV1, FVC ಮತ್ತು FEV1/FVC ಅನ್ನು 45-90 ವರ್ಷದ ಭಾರತೀಯ ವಯಸ್ಕರ LASI ಉಲ್ಲೇಖ ಮೌಲ್ಯಗಳೊಂದಿಗೆ ಹೋಲಿಸುತ್ತದೆ. ಫಲಿತಾಂಶಗಳನ್ನು ಲಕ್ಷಣಗಳು, ಪರೀಕ್ಷೆ, ಪರೀಕ್ಷಾ ಗುಣಮಟ್ಟ ಮತ್ತು ಸ್ಥಳೀಯ ಮಾರ್ಗದರ್ಶನದೊಂದಿಗೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬೇಕು.', 'LASI ಉಲ್ಲೇಖ ಸಮೀಕರಣಗಳು; ಸ್ಥಳೀಯ ವೈದ್ಯಕೀಯ ಪರಿಶೀಲನೆ ಅಗತ್ಯ.', 'v1'),
('warning-symptoms', 'kn', 'patient', 'ತುರ್ತು ಸಹಾಯ ಯಾವಾಗ ಪಡೆಯಬೇಕು', 'ತೀವ್ರ ಉಸಿರಾಟ ತೊಂದರೆ, ಎದೆ ನೋವು, ಮೂರ್ಛೆ, ಗೊಂದಲ, ನೀಲಿ ತುಟಿ, ರಕ್ತದ ಕೆಮ್ಮು, ಅಕಸ್ಮಾತ್ ದೌರ್ಬಲ್ಯ ಅಥವಾ ವೇಗವಾಗಿ ಹದಗೆಡುವ ಅನಾರೋಗ್ಯದಲ್ಲಿ ತಕ್ಷಣ ಸಹಾಯ ಪಡೆಯಿರಿ.', 'ಸುರಕ್ಷತಾ ಶಿಕ್ಷಣ; ತುರ್ತು ಸೇವೆಗಳ ಪರ್ಯಾಯವಲ್ಲ.', 'v1'),
('visit-preparation', 'kn', 'patient', 'ಭೇಟಿಗೆ ಸಿದ್ಧತೆ', 'ಔಷಧಿ ಪಟ್ಟಿ, ಹಿಂದಿನ ವರದಿಗಳು, ಲಸಿಕೆ ಇತಿಹಾಸ, ಲಕ್ಷಣಗಳ ಟಿಪ್ಪಣಿ, ಬೀಳುವಿಕೆ ಇತಿಹಾಸ, ಆರೈಕೆದಾರರ ಚಿಂತೆಗಳು ಮತ್ತು ಪ್ರಶ್ನೆಗಳನ್ನು ತಂದುಕೊಳ್ಳಿ.', 'ಹಂಚಿಕೊಂಡ ನಿರ್ಧಾರಕ್ಕೆ ರೋಗಿ ಶಿಕ್ಷಣ.', 'v1')
on conflict (slug, language_code, role_context, version) do nothing;
