project_id = "clinician-ageing-tool"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:4173"
additional_redirect_urls = ["https://clinician-ageing-tool.vercel.app"]
jwt_expiry = 3600
enable_signup = true

[db]
port = 54322
shadow_port = 54320
major_version = 15
